### ISSUE TITLE
Error in your GraphQL query

### ISSUE THREAD

**Issue by guanacone** [CrystallizeAPI/crystallize-gatsby-boilerplate#15]
`npm run dev` fails. See PrtScr for error messages.

![Screenshot from 2021-04-29 21-31-26](https://user-images.githubusercontent.com/11678477/116700146-b35da200-a983-11eb-8efd-756badc415af.png)

**Comment by hakonkrogh** [comment]
Resolved in https://github.com/CrystallizeAPI/crystallize-gatsby-boilerplate/commit/95107c305acc4362760950d85576258ad0f1ee0a
